### ISSUE TITLE
Aceitar `graus` com sinônimo de `deg`

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [DesignLiquido/FolEs#116]
Atualmente, aceitamos um modificador com a unidade `deg`:

```sass
lmht {
    origem-imagem-borda: gradiente-linear(90deg, verde, amarelo);
```

Devemos aceitar `graus` como sinônimo:

```sass
lmht {
    origem-imagem-borda: gradiente-linear(90graus, verde, amarelo);
```

**Comment by pedrowindisch** [comment]
Olá!

Estava dando uma olhada no código e parece que são vários os modificadores que aceitam valores com quantificadores com a unidade `deg`.

Seria uma boa solução a classe [`Simbolo`](https://github.com/DesignLiquido/FolEs/blob/principal/fontes/lexador/simbolo.ts#L18), ao ser instanciada, "traduzir" o lexema para o correspondente em inglês?

No caso, imaginei algo assim:

```typescript
    [...]

    constructor(
        tipo: string, 
        lexema: string, 
        literal: any, 
        linha: number, 
        colunaInicial: number, 
        colunaFinal: number
    ) {
        this.tipo = tipo;
        this.lexema = sinonimos[this.tipo]?.[lexema] ?? lexema; // sendo o objeto sinonimos do tipo Partial<Record<keyof typeof tiposDeSimbolos [tipos-de-simbolos/foles], Record<string, string>>
        this.literal = literal;
        this.linha = linha;
        this.colunaInicial = colunaInicial;
        this.colunaFinal = colunaFinal;
    }

    [...]
```

**Comment by leonelsanchesdasilva** [comment]
Olá, @pedrowindisch 👋 

Não porque FolEs é bidirecional: podemos traduzir tanto de FolEs para CSS quanto de CSS para FolEs.

**Comment by leonelsanchesdasilva** [comment]
Resolvido em https://github.com/DesignLiquido/FolEs/pull/123
