### ISSUE TITLE
Implementar Store Pattern para instanciar modificador dinamicamente

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [DesignLiquido/FolEs#2]
A ideia é isso aqui: https://buddhiamigo.medium.com/how-to-create-typescript-classes-dynamically-b29ca7767ee5

A Store deve ser chamada pelo Avaliador Sintático.

**Comment by VitBrandao** [comment]
Atividade concluída no PR: https://github.com/DesignLiquido/FolEs/pull/4
