### ISSUE TITLE
Permitir que Avaliador Sintático aceite valores numéricos SEM QUANTIFICADOR

### ISSUE THREAD

**Issue by VitBrandao** [DesignLiquido/FolEs#57]
O Avaliador Sintático ainda retorna um erro quando o valor passado a um seletor é somente **numérico**.

No caso, se tentarmos fazer:
```
corpo {
  linhas-superiores: 2;
}
```

O Avaliador retorna o seguinte erro:
`Esperado ';' após declaração de valor de modificador 'linhas-superiores'.`

Isso se dá devido à sequência de operações no método `declaracaoDeclaracao`, quando o Avaliador Sintático **tenta buscar por um quantificador** - que para esses casos, é inexistente. Vale lembrar que existem **cerca de 30 seletores que aceitam somente números como valores** (lista completa em `/testes/listas/valor-numerico.ts`).

**Objetivo da Issue**: implementar a lógica para que o Avaliador reconheça o número por si só como valor, sem esperar um quantificador.

**Comment by leonelsanchesdasilva** [comment]
@VitBrandao Isso ainda é relevante?

**Comment by VitBrandao** [comment]
Issue solucionada no PR https://github.com/DesignLiquido/FolEs/pull/112
