### ISSUE TITLE
Permitir que modificadores de Atribuição Abreviada recebam MÚLTIPLOS VALORES

### ISSUE THREAD

**Issue by VitBrandao** [DesignLiquido/FolEs#59]
O grupo de seletores de Atribuição Abreviada já estão com as devidas validações de valores feitas internamente em cada modificador. 

Porém, é necessário pensar em uma lógica para que esses múltiplos valores sejam aceitos - o que passa por refatorar o **Lexador**, **Avaliador Sintático** e **Tradutor**.

**Comment by leonelsanchesdasilva** [comment]
@VitBrandao Isso ainda é relevante?

**Comment by VitBrandao** [comment]
### PONTO IMPORTANTE

Todos os modificadores que integram esse grupo de Atribuição Abreviada já possuem atualmente uma lógica para aceitarem todos os valores listados na documentação, mas **só é possível atribuir UM único valor para cada modificador**.  

A solução dessa Issue visa que cada um desses modificadores **passe a aceitar múltiplos valores separados por um espaço em branco**, tal qual o exemplo abaixo:

Ex.:
```
tamanho-fundo: auto 50%;
```

Nos moldes atuais, `tamanho-fundo` aceita tanto `auto` quanto `50%`, mas não ambos ao mesmo tempo.

DOCUMENTAÇÃO PARA SE BASEAR: https://developer.mozilla.org/pt-BR/docs/Web/CSS/Shorthand_properties

**Comment by VitBrandao** [comment]
Modificadores que dependem dessa implementação para funcionarem 100% tal qual os referidos seletores CSS:

```
ajustar-tamanho-fonte
borda
borda-direita
borda-em-bloco
borda-em-linha
borda-esquerda
borda-inferior
borda-mascara
borda-superior
combinar-texto-vertical
comportamento-rolagem-mouse
configurações-variação-fonte
contém
cursor
decoração-linha-texto
definir-contador
deslocamento-em-âncora
deslocar-pontuação
duração-transição
ênfase-texto
escala
espaçamento
espaço-borda
esquema-cor
estender-borda-imagem
estilo-fonte
estilo-lista
exibição
fatiar-imagem-borda
fim-coluna-em-grade
fim-linha-em-grade
flex-fluxo
fluxo-em-grade
fonte-texto
girar
grade
incrementar-contador
indentação-texto
início-coluna-em-grade
início-linha-em-grade
justificar-itens
largura-imagem-borda
linha-em-grade
ordem-pintura
origem-máscara
origem-perspectiva
posição-ênfase-texto
posição-objeto
posição-texto-sublinhado
posição-vertical-fundo
posicionar-conteúdo
posicionar-itens
posicionar-se
raio-direito-borda-superior
raio-direito-borda-inferior
raio-esquerdo-borda-inferior
raio-esquerdo-borda-superior
recortar-margem-vazada
repetição-borda-máscara
repetir-fundo
repetir-máscara
rotação-deslocamento
sombra-caixa
tamanho-fundo
tamanho-máscara
transformar-origem
variação-fonte-asiática
variação-fonte-numérica
```

**TOTAL**: 67 Modificadores

**Comment by VitBrandao** [comment]
Issue solucionada no PR https://github.com/DesignLiquido/FolEs/pull/124
