### ISSUE TITLE
Mapear e solucionar os TODOs dos Modificadores

### ISSUE THREAD

**Issue by VitBrandao** [DesignLiquido/FolEs#63]
Os arquivos dos modificadores estão com vários trechos comentados e destacados pela palavra **TODO** (a fazer) indicando **quais implementações ainda estão faltando** para cada um dos modificadores. A maioria dos TODOs envolve atribuições específicas de valores aos seletores - soluções que passam por melhorias no Lexador e no Avaliador Sintático. 

Para mapear os TODOs, recomendo a instalação da extensão [TODO Highlight](https://github.com/wayou/vscode-todo-highlight) recomendada a mim pelo Leonel. Não precisa baixar pelo repositório - é mais fácil pesquisar na aba 'Extensões' do VS Code e baixar por lá. 

Abro essa Issue para que todos(as) os(as) autores(as) da FolEs estejam cientes das implementações extras que ainda precisam ser realizadas.

**Comment by leonelsanchesdasilva** [comment]
@VitBrandao Atualmente temos 106 TODOs no projeto. Gostaria que você por favor voltasse neles e tentasse resolver.

**Comment by VitBrandao** [comment]
### MAPEAMENTO DOS TO-DOS

Após revisão geral, **101 dos 106** TO-DOs do repositório agora serão **divididos em 7 grupos**:

1. Modificadores de **Atribuição Abreviada** que recebem **múltiplos valores separados por espaço** (Já há uma Issue aberta);
**ABRANGÊNCIA**: 68 modificadores

2. Modificadores que recebem valores **separados por vírgula**;
**ABRANGÊNCIA**: 3 modificadores

3. Modificadores que recebem valores **separados por barra**;
**ABRANGÊNCIA**: 6 modificadores

4. Modificadores que recebem valores **do tipo CUSTOM-IDENT**;
**ABRANGÊNCIA**: 12 modificadores

5. Modificadores que recebem valores **do tipo STRING**;
**ABRANGÊNCIA**: 6 modificadores

6. Modificadores que recebem **funções especiais** ainda não implementadas em FolEs;
**ABRANGÊNCIA**: 11 modificadores

7. Modificadores que recebem **valores especiais** - casos específicos que não se encaixam nos demais grupos;
**ABRANGÊNCIA**: 8 modificadores
 
O objetivo agora é abrir uma Issue para cada um desses grupos, para estudar as soluções e garantir o funcionamento completo desses 101 modificadores.

**Comment by VitBrandao** [comment]
Mapeamento realizado e distribuído em 7 novas Issues no repositório.
