### ISSUE TITLE
Passar `pragmas` no `super` do construtor de todas as estruturas

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [DesignLiquido/FolEs#94]
Na minha última PR, fiz a seguinte modificação: https://github.com/DesignLiquido/FolEs/pull/92/files#diff-2ca6284adffa8f97cb7e166695ea58e619647532031c870c63306227850dae90

A ideia aqui é fazer a mesma modificação para os demais modificadores.

**Comment by VitBrandao** [comment]
Solução implementada no PR https://github.com/DesignLiquido/FolEs/pull/95
